### ISSUE TITLE
conda-forge lists __win as a MatchSpec dependency  for httpie=2.2.0 preventing installation on linux-64

### ISSUE THREAD

**Issue by giftculture** [httpie/cli#1564]
## Checklist

- [x ] I've searched for similar issues.
- [x ] I'm using the latest version of HTTPie.

---

## Minimal reproduction code and steps

conda search -c conda-forge httpie=3.2.2 --json

## Current result

 "httpie": [
    {
      "arch": null,
      "build": "pyh95a074a_0",
      "build_number": 0,
      "channel": "https://conda.anaconda.org/conda-forge/noarch",
      "constrains": [],
      "depends": [
        "__win",
        "charset-normalizer >=2.0.0",
        "colorama >=0.2.4",
        "defusedxml >=0.6.0",
        "multidict >=4.7.0",
        "pip",
        "pygments >=2.5.2",
        "python >=3.8",
        "requests >=2.22.0",
        "requests-toolbelt >=0.9.1",
        "rich >=9.10.0",
        "setuptools"
      ],
      "fn": "httpie-3.2.2-pyh95a074a_0.conda",
      "license": "BSD-3-Clause",
      "license_family": "BSD",
      "md5": "c6ee62b8fd87c36e8a8536419bcf1222",
      "name": "httpie",
      "noarch": "python",
      "package_type": "noarch_python",
      "platform": null,
      "sha256": "e7c97481da722bb1df801b69193a1f6651cfe44c42face0bba642cf7858467a0",
      "size": 93973,
      "subdir": "noarch",
      "timestamp": 1684775341975,
      "url": "https://conda.anaconda.org/conda-forge/noarch/httpie-3.2.2-pyh95a074a_0.conda",
      "version": "3.2.2"
    },

$ conda install -c conda-forge httpie=3.2.2
Channels:
 - conda-forge
 - nodefaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: -
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides __win needed by httpie-3.2.2-pyh95a074a_0

Could not solve for environment specs
The following package could not be installed
└─ httpie 3.2.2**  is not installable because it requires
   └─ __win, which is missing on the system.
…

## Expected result

__win should not be a MatchSpec requirement on linux-64 systems

**Comment by siddharth07-ui** [comment]
Hi, I have tried this too and found an exact issue on my machine. Below are the details for my machine and the architecture too.
==================================
conda install -c conda-forge httpie=3.2.2
Channels:
 - conda-forge
 - microsoft
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides __win needed by httpie-3.2.2-pyh95a074a_0

Could not solve for environment specs
The following package could not be installed
└─ httpie 3.2.2**  is not installable because it requires
   └─ __win, which is missing on the system.
==================================
uname -srm
Linux 6.5.0-21-generic x86_64
==================================
It s giving a requirement as '__win' while there should be a requirement for '"__unix" as seen in version 3.2.1

**Comment by Ousret** [comment]
I highly doubt that the feedstock/conda for HTTPie is broken. But if it is, HTTPie do not maintains it.
Please retry out of a clean conda environment and if it persist, I suggest to open an issue at conda feedstock to seek for support.

regards,
