### ISSUE TITLE
Headers being droped

### ISSUE THREAD

**Issue by iax7** [httpie/cli#502]
Not sure why is this happening, but when I got a redirect, the header's Authorization token is dropped, causing an unauthorized error in the final server.

Output: http://pastiebin.com/57ad0ec278c36

This does not happen with cURL

**Comment by sigmavirus24** [comment]
Hi @iax7!

This is fundamentally not HTTPie's fault and actually a Really Good Feature. Let me explain this in two parts:

1. Not HTTPie's fault: HTTPie uses [Requests](/kennethreitz/requests) which does this for all of its users for security.
2. This is a Really Good Feature because on a redirect, if you allow your client to handle those for you, you cannot be certain that your sensitive information (in that Authorization header) is going to *not* end up in the wrong place (sent to a server that should not have that information).

The difference with cURL comes from the fact that cURL does not handle redirects for you by default. It leaves those up to the user. And when you tell curl to follow redirects, you are implicitly agreeing to the documented insecure behaviour.

In my opinion, you should handle redirects in this case yourself since you appear to be confident that you will not run into any problems sending your authorization token.

**Comment by iax7** [comment]
Thank you @sigmavirus24 for your awesome reply.

Actually what you say makes total sense, for security reasons. 

However, I didn't find it in the documentation. Is there a way to replicate cURL's behavior? It's ok to be protected by default. But a way to overcome this should be handy when you're sure that you can trust a corporate network.

**Comment by sigmavirus24** [comment]
> However, I didn't find it in the documentation.

Yeah I suspect it hasn't occurred to anyone to document this. Why don't you send a PR documenting this as known and expected behaviour? 😄 

> Is there a way to replicate cURL's behavior?

I don't know it off the top of my head.

So I just tested HTTPie, 0.9.4:

```
~❯❯❯ http --all --history-print Hhb --print Hhb --follow GET 'https://httpbin.org/redirect/2' 'Authorizaton: token'
GET /redirect/2 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorizaton:  token
Connection: keep-alive
Host: httpbin.org
User-Agent: HTTPie/0.9.4

HTTP/1.1 302 FOUND
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 247
Content-Type: text/html; charset=utf-8
Date: Fri, 12 Aug 2016 16:10:09 GMT
Location: /relative-redirect/1
Server: nginx

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="/relative-redirect/1">/relative-redirect/1</a>.  If not click the link.

GET /relative-redirect/1 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorizaton:  token
Connection: keep-alive
Host: httpbin.org
User-Agent: HTTPie/0.9.4

HTTP/1.1 302 FOUND
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 0
Content-Type: text/html; charset=utf-8
Date: Fri, 12 Aug 2016 16:10:09 GMT
Location: /get
Server: nginx



GET /get HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorizaton:  token
Connection: keep-alive
Host: httpbin.org
User-Agent: HTTPie/0.9.4

HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 259
Content-Type: application/json
Date: Fri, 12 Aug 2016 16:10:09 GMT
Server: nginx

{
    "args": {},
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Authorizaton": "token",
        "Host": "httpbin.org",
        "User-Agent": "HTTPie/0.9.4"
    },
    "origin": "10.0.0.1",
    "url": "https://httpbin.org/get"
}
```

So I think we made Requests a bit smarter at some point where we allow the same domain to retain credentials. Is this roughly how you're using HTTPie as well?
